### ISSUE TITLE
Woocommerce Coupon Payout

### ISSUE THREAD

**Issue by ashneverdawn** [wp-insider/affiliates-manager-plugin#7]
I need to have an a different payout option. In my woocommerce store, on checkout, I need an option to use all/part of the balance toward the purchase. Alternatively, the payout could be made in the form of a woocommerce coupon for one-time use in the store. How can this be achieved?

**Comment by affmngr** [comment]
Hi, Unfortunately this cannot be implemented into the plugin at the moment.
